id: multi_apps_reiew_ingestion
namespace: steam_review_pipeline

description: This yaml schedule to run  multiple steam raw review ingestion task to the db. Recommend running it every 30 mins

inputs:
  - id: app_id
    type: INT
    required: true

  - id: max_pages
    type: INT
    required: true
    defaults: 50
  - id: num_per_page
    type: INT
    required: true
    defaults: 100


triggers:

  # Dota 2
  - id: schedule_ingest_dota2_reviews
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"
    timezone: America/Toronto #withoutimezone it will use utc
    inputs:
      app_id: 570
      max_pages: 50
      num_per_page: 100

  # CS2
  - id: schedule_ingest_cs2_reviews
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"
    timezone: America/Toronto
    inputs:
      app_id: 730
      max_pages: 50
      num_per_page: 100    

  # APEX
  - id: schedule_ingest_apex_reviews
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"
    timezone: America/Toronto
    inputs:
      app_id: 1172470
      max_pages: 50
      num_per_page: 100     

tasks:
  - id: run_ingestion_container
    type: io.kestra.plugin.docker.Run
    containerImage: steam-review-ingestion:latest
    # allow kestra to run the docker image in side the docker compose network
    networkMode: comp4905_project_default
    env:
      DATABASE_URL: "postgresql+psycopg://root:root@pgdatabase:5432/steam_review"
    commands:
      - "--app_id"
      - "{{ inputs.app_id }}"
      - "--num_per_page"
      - "{{ inputs.num_per_page }}"
      - "--max_pages"
      - "{{ inputs.max_pages }}"